/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DemiUser = IDL.Record({
  'id' : IDL.Nat,
  'role' : UserRole,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'joinDate' : IDL.Text,
  'feeStatus' : IDL.Text,
  'parentPhone' : IDL.Text,
  'section' : IDL.Text,
  'email' : IDL.Text,
  'attendancePct' : IDL.Nat,
  'grade' : IDL.Nat,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'admissionNo' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'parentName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const SchoolRole = IDL.Variant({
  'Teacher' : IDL.Null,
  'Student' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'schoolRole' : SchoolRole,
  'username' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDemiUser' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, UserRole],
      [DemiUser],
      [],
    ),
  'addStudent' : IDL.Func([Student], [Student], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalStudents' : IDL.Nat, 'totalTeachers' : IDL.Nat })],
      ['query'],
    ),
  'getDemiUserById' : IDL.Func([IDL.Nat], [IDL.Opt(DemiUser)], ['query']),
  'getStudentById' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'removeDemiUser' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoUsers' : IDL.Func([], [], []),
  'seedStudents' : IDL.Func([IDL.Vec(Student)], [], []),
  'totalDemiUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'updateDemiUser' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, UserRole],
      [DemiUser],
      [],
    ),
  'updateStudent' : IDL.Func([Student], [Student], []),
  'validateToken' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DemiUser = IDL.Record({
    'id' : IDL.Nat,
    'role' : UserRole,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'joinDate' : IDL.Text,
    'feeStatus' : IDL.Text,
    'parentPhone' : IDL.Text,
    'section' : IDL.Text,
    'email' : IDL.Text,
    'attendancePct' : IDL.Nat,
    'grade' : IDL.Nat,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'admissionNo' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'parentName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const SchoolRole = IDL.Variant({
    'Teacher' : IDL.Null,
    'Student' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'schoolRole' : SchoolRole,
    'username' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDemiUser' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, UserRole],
        [DemiUser],
        [],
      ),
    'addStudent' : IDL.Func([Student], [Student], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalStudents' : IDL.Nat, 'totalTeachers' : IDL.Nat })],
        ['query'],
      ),
    'getDemiUserById' : IDL.Func([IDL.Nat], [IDL.Opt(DemiUser)], ['query']),
    'getStudentById' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'removeDemiUser' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoUsers' : IDL.Func([], [], []),
    'seedStudents' : IDL.Func([IDL.Vec(Student)], [], []),
    'totalDemiUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'updateDemiUser' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, UserRole],
        [DemiUser],
        [],
      ),
    'updateStudent' : IDL.Func([Student], [Student], []),
    'validateToken' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };