/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DemiUser {
  'id' : bigint,
  'role' : UserRole,
  'lastName' : string,
  'firstName' : string,
}
export type SchoolRole = { 'Teacher' : null } |
  { 'Student' : null } |
  { 'Admin' : null };
export interface Student {
  'id' : bigint,
  'dob' : string,
  'joinDate' : string,
  'feeStatus' : string,
  'parentPhone' : string,
  'section' : string,
  'email' : string,
  'attendancePct' : bigint,
  'grade' : bigint,
  'address' : string,
  'gender' : string,
  'admissionNo' : string,
  'phone' : string,
  'lastName' : string,
  'parentName' : string,
  'firstName' : string,
}
export interface UserProfile {
  'schoolRole' : SchoolRole,
  'username' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDemiUser' : ActorMethod<[bigint, string, string, UserRole], DemiUser>,
  'addStudent' : ActorMethod<[Student], Student>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStudent' : ActorMethod<[bigint], undefined>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    { 'totalStudents' : bigint, 'totalTeachers' : bigint }
  >,
  'getDemiUserById' : ActorMethod<[bigint], [] | [DemiUser]>,
  'getStudentById' : ActorMethod<[bigint], [] | [Student]>,
  'getStudentCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], [] | [string]>,
  'logout' : ActorMethod<[string], undefined>,
  'removeDemiUser' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoUsers' : ActorMethod<[], undefined>,
  'seedStudents' : ActorMethod<[Array<Student>], undefined>,
  'totalDemiUsers' : ActorMethod<[], bigint>,
  'updateDemiUser' : ActorMethod<[bigint, string, string, UserRole], DemiUser>,
  'updateStudent' : ActorMethod<[Student], Student>,
  'validateToken' : ActorMethod<[string], [] | [Principal]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];